version: '3.8'

services:
  #pythonapp:
    #container_name: DockerTestWithPython
    #build: ./
    #command: /bin/sh -c "python3 ./main.py && python3 ./TwinAddRoute.py"
    #command: /bin/sh -c "python3 ./main.py"

  talker3:
    build:
      dockerfile: dockerfile
    #command: /bin/sh -c "python3 ~/ros2_ws/src/py_srvcli/py_srvcli/TwinCAT_Add_Route.py"

    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - my-bridge-network

networks:
  my-bridge-network:
    driver: bridge