version: '3.8'

services:
  #pythonapp:
    #container_name: DockerTestWithPython
    #build: ./
    #command: /bin/sh -c "python3 ./main.py && python3 ./TwinAddRoute.py"
    #command: /bin/sh -c "python3 ./main.py"

  talker3:
    build:
      dockerfile: dockerfile
    #command: ros2 run demo_nodes_cpp talker
    command: /bin/sh -c "python3 ~/ros2_ws/src/py_srvcli/py_srvcli/TwinCAT_Add_Route.py"